format = """
$directory\
$git_branch\
$git_state\
$git_status\
$fill\
$battery\
$java\
$nodejs\
$golang\
$helm\
$terraform\
$package\
$aws\
$azure\
$cmd_duration\
$jobs\
$line_break\
$character"""

palette = "catppuccin_mocha"

[directory]
truncation_length = 2
truncate_to_repo = false
home_symbol = "anadinema"

[fill]
symbol = ' '

[[battery.display]]
threshold = 25
style = 'bold red'

[java]
symbol = '☕'
detect_folders = [ 'app', 'library' ]

[cmd_duration]
min_time = 100
format = ' 🕓 [$duration](bold yellow)'

[package]
disabled = true

[aws]
symbol = '  '
format = 'at [$symbol($profile )(\($region\))]($style)'

[terraform]
format = '[$symbol$version (\($workspace\))]($style) '

[aws.profile_aliases]
main = 'ship-main'
spt = 'sp-test'
spp = 'sp-main'

[aws.region_aliases]
eu-west-1 = 'ireland'
eu-north-1 = 'stockholm'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
