#!/usr/bin/env bash

set -euxo pipefail

if [[ ! -e /opt/homebrew/bin/brew ]]; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

brew bundle install --verbose --file box/personal-macbook/pkgs/brewfile

just bootstrap "personal-macbook"
