#!/usr/bin/env bash

set -euxo pipefail

DOTBOT_BOX=$1

if [[ ! -e /opt/homebrew/bin/brew ]]; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

brew bundle install --file box/$DOTBOT_BOX/pkgs/brewfile

just bootstrap "$DOTBOT_BOX"
